# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hi! I'm Aly Fluckey
email: fluckeya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Engineering leader focused on product-aligned teams, sustainable execution,
  and building high-trust environments where engineers thrive.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wtfluckey.com" # the base hostname & protocol for your site
twitter_username: wtfluckey
github_username: wtfluckey

# Build settings
markdown: kramdown
exclude: ["README.md"]
